# TELEGRAM
TELEGRAM_TOKEN = "YOUR TELEGRAM TOKEN"
CHANNEL_ID = "-1001948532295"

# AMAZON
AMAZON_ACCESS_KEY = "YOUR AMAZON ACCESS KEY FROM AFFILIATE PROGRAM"
AMAZON_SECRET_KEY = "YOUR AMAZON SECRET KEY FROM AFFILIATE PROGRAM"
PARTNER_TAG = "ironman1122-21"
AMAZON_HOST = "webservices.amazon.in" #change to your country
AMAZON_REGION = "eu-west-1" #change to your country

